/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TransactionsIndexImport } from './routes/transactions/index'
import { Route as CategoriesIndexImport } from './routes/categories/index'

// Create/Update Routes

const TransactionsIndexRoute = TransactionsIndexImport.update({
  path: '/transactions/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesIndexRoute = CategoriesIndexImport.update({
  path: '/categories/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/categories/': {
      id: '/categories/'
      path: '/categories/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  CategoriesIndexRoute,
  TransactionsIndexRoute,
})

/* prettier-ignore-end */
